on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: cn
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: generate
        uses: docker://ccr.ccs.tencentyun.com/xiaoqidun/build:latest
        with:
          args: -f build.sh -i gitcz.go -o release/gitcz
      - name: docker goenv
        uses: docker://ccr.ccs.tencentyun.com/xiaoqidun/goenv:latest
        env:
          GIT_SERVER: ${{ secrets.git_server }}
          GIT_USER: ${{ secrets.git_user }}
          GIT_TOKEN: ${{ secrets.git_token }}
        with:
          args: bash build.sh
      - name: upload to cos
        uses: xiaoqidun/gocos@main
        with:
          secret_id: ${{ secrets.cos_secret_id }}
          secret_key: ${{ secrets.cos_secret_key }}
          bucket_url: ${{ secrets.cos_bucket_url }}
          source_path: release
          target_path: product/gitcz
          strip_prefix: release